# Generated by Django 3.0.5 on 2020-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(choices=[('0,25', '0,25'), ('0,5', '0,5'), ('1', '1')], default='0.25', max_length=20),
        ),
    ]
