# Generated by Django 3.0.5 on 2020-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200502_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='I',
        ),
    ]
