# Generated by Django 3.0.5 on 2020-05-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200502_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='I',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
