# Generated by Django 3.0.5 on 2020-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200503_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAndPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(to='shop.ValueAndPrices'),
        ),
    ]
