# Generated by Django 3.0.5 on 2020-05-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueandprices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.Product'),
        ),
    ]
