# Generated by Django 3.0.5 on 2020-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200504_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='valueandprices',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
