# Generated by Django 3.0.5 on 2020-05-20 21:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200517_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAndPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Адрес и номер телефона',
                'verbose_name_plural': 'Адреса и номера телефонов',
            },
        ),
        migrations.AlterField(
            model_name='valueandprices',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
