# Generated by Django 3.0.5 on 2020-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200520_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressandphone',
            options={'verbose_name': 'Адрес и номер телефона', 'verbose_name_plural': 'Адреса и номера теле'},
        ),
        migrations.AlterField(
            model_name='addressandphone',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
