# Generated by Django 3.0.5 on 2020-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200520_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressandphone',
            options={'verbose_name': 'Адрес и номер телефона', 'verbose_name_plural': 'Адреса и номера телефонов'},
        ),
        migrations.AddField(
            model_name='addressandphone',
            name='map_image',
            field=models.ImageField(blank=True, upload_to='map_image'),
        ),
    ]
