# Generated by Django 3.0.5 on 2020-05-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200520_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueandprices',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%d/%m'),
        ),
    ]
