# Generated by Django 3.0.5 on 2020-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='products',
            field=models.ManyToManyField(related_name='subcategories', to='shop.Product'),
        ),
    ]
