# Generated by Django 3.0.5 on 2020-06-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200602_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort',
        ),
        migrations.CreateModel(
            name='SubcategoryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_for_sub', to='shop.Subcategory')),
            ],
        ),
    ]
