# Generated by Django 3.0.5 on 2020-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200602_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='products',
            field=models.ManyToManyField(related_name='subcategories', to='shop.Product'),
        ),
        migrations.DeleteModel(
            name='SubcategoryContent',
        ),
    ]
