# Generated by Django 3.0.5 on 2020-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200602_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
