# Generated by Django 3.0.5 on 2020-05-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200517_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Доставка курьером', 'Доставка курьером'), ('Самовывоз', 'Самовывоз')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='verification',
            field=models.CharField(choices=[('Смс', 'Смс'), ('Звонок оператора', 'Звонок оператора')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
