# Generated by Django 3.0.5 on 2020-05-23 21:53

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200523_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
