# Generated by Django 3.0.5 on 2020-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200523_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
