# Generated by Django 3.0.5 on 2020-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200523_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Адресс',
                'verbose_name_plural': 'Адресса',
            },
        ),
    ]
