# Generated by Django 3.0.5 on 2020-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200531_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopadress',
            options={'verbose_name': 'Адресс', 'verbose_name_plural': 'Адресса'},
        ),
        migrations.AddField(
            model_name='order',
            name='adress_choice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
